### ISSUE TITLE
1/4 screen render on retina screens

### ISSUE THREAD

**Issue by erango** [nickzman/helios#2]
<img width="299" alt="Screen Shot 2020-04-21 at 19 25 31" src="https://user-images.githubusercontent.com/6323368/79888886-f3e81e80-8405-11ea-93e2-04a66229bba5.png">

**Comment by nickzman** [comment]
I know, and it's because Apple changed OpenGL views in Catalina so they expect the viewport to draw at 144 DPI instead of 72 on a HiDPI display, and this is what happens if it's programmed to run at 72 and rely on the old default behavior.

I can either enforce the old behavior, or make sure it works with HiDPI if I can find the time.

**Comment by erango** [comment]
I really want this to work :D If you can point me in the right direction I can make a PR

**Comment by nickzman** [comment]
The glViewport() needs to be set to the view bounds * the view's window's screen's backingScaleFactor. And then -wantsBestResolutionOpenGLSurface needs to be always turned on so the viewport is correct in Mojave and earlier.

If it just doesn't work at 2x for whatever reason, then at the least, disabling -wantsBestResolutionOpenGLSurface will fix the viewport problem.

**Comment by TimAlberry** [comment]
I don't know what a PR is (I am not a developer), but a fixed version of what is in my humble opinion the most hypnotic screensaver ever, especially this late in the day... would be... wonder-full. 1.6?

**Comment by erango** [comment]
It's been about 10 years since I last did anything with C++ but I'm setting up an environment and doing this. I love it too and I want it to be perfect on retina screens too 😄

**Comment by TimAlberry** [comment]
Awe...some!

**Comment by erango** [comment]
This line causes the build to fail and I'm having trouble understanding it:
`par.ilist = new ion[par.dIons](&par);`
Does this mean "create a new array called ion with the length of par.dIons, and initialize it with par"? I don't know what to make of it since par is a struct.
😵

**Comment by erango** [comment]
OK, I'm good to go. Ready to make a PR, also have a working build. @nickzman Would you like to give me access to contribute?

**Comment by nickzman** [comment]
You don't need access. You create PRs on Github by forking a project, checking in your changes, and then creating a PR against the master repository.

**Comment by erango** [comment]
Cool! Never done it like that before.

**Comment by TimAlberry** [comment]
How are things progeessing on this? Or maybe fix has been released somewhere else that I have missed (as I see mention of "forking" in earleir posts)?

**Comment by nickzman** [comment]
I've completely revamped the screen saver by bringing the code base up to date with the Windows version, and modernizing the product and the build. The latest changes add HiDPI and 60 FPS support. If you have Xcode 11.x, please try it out. Otherwise, I'll have binaries out soon.

**Comment by TimAlberry** [comment]
I hope everyone on this thread is keeping safe. And I also wondered if there is any news on creation of the binaries (as I know zip about Xcode 11! ;)

**Comment by nickzman** [comment]
The binaries came out two weeks ago.
